{{- if .Values.serviceX.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceX.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceX.name }}
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "python-instrumentation"
      labels:
        app: {{ .Values.serviceX.name }}
    spec:
      containers:
        - name: {{ .Values.serviceX.name }}
          image: {{ .Values.serviceX.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVICE_NAME
              value: {{ .Values.serviceX.name | quote }}
            - name: SERVICE_Y_URL
              value: {{ printf "http://%s:%v/process" .Values.serviceY.name .Values.serviceY.port | quote }}
          ports:
            - containerPort: {{ .Values.serviceX.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceX.name }}
spec:
  selector:
    app: {{ .Values.serviceX.name }}
  ports:
    - name: http
      port: {{ .Values.serviceX.port }}
      targetPort: {{ .Values.serviceX.port }}
  type: ClusterIP
{{- end }}
