{{- if .Values.serviceY.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceY.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceY.name }}
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "python-instrumentation"
      labels:
        app: {{ .Values.serviceY.name }}
    spec:
      containers:
        - name: {{ .Values.serviceY.name }}
          image: {{ .Values.serviceY.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVICE_NAME
              value: {{ .Values.serviceY.name | quote }}
            - name: REDIS_HOST
              value: {{ .Values.redis.serviceName | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.otelOperatorCollector.tracesEndpoint | quote }}
          ports:
            - containerPort: {{ .Values.serviceY.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceY.name }}
spec:
  selector:
    app: {{ .Values.serviceY.name }}
  ports:
    - name: http
      port: {{ .Values.serviceY.port }}
      targetPort: {{ .Values.serviceY.port }}
  type: ClusterIP
{{- end }}
